// Generated by ReScript, PLEASE EDIT WITH CARE


function swap(c) {
  if (Math.random() < 0.5) {
    return c.toLocaleLowerCase();
  } else {
    return c.toLocaleUpperCase();
  }
}

function mockify(inputString) {
  return inputString.split("").map(swap).reduce((function (acc, element) {
                return acc + element;
              }), "");
}
/* No side effect */
