// Generated by ReScript, PLEASE EDIT WITH CARE


function swap(c, threshold) {
  switch (c) {
    case "\n" :
        return [
                "\\n",
                0
              ];
    case " " :
        return [
                c,
                0
              ];
    case "\"" :
        return [
                "\\\"",
                0
              ];
    default:
      if (Math.random() < threshold) {
        return [
                c.toLocaleLowerCase(),
                -1
              ];
      } else {
        return [
                c.toLocaleUpperCase(),
                1
              ];
      }
  }
}

function mockify_helper(_completed, _remaining, _consecutiveUppers) {
  while(true) {
    var consecutiveUppers = _consecutiveUppers;
    var remaining = _remaining;
    var completed = _completed;
    if (remaining === "") {
      return completed;
    }
    var threshold = 0.5 + consecutiveUppers * 0.17;
    var match = swap(remaining[0], threshold);
    var nextChar = match[0];
    switch (match[1]) {
      case -1 :
          _consecutiveUppers = Math.min(consecutiveUppers - 1 | 0, -1);
          _remaining = remaining.slice(1);
          _completed = completed + nextChar;
          continue ;
      case 0 :
          break;
      case 1 :
          _consecutiveUppers = Math.max(consecutiveUppers + 1 | 0, 1);
          _remaining = remaining.slice(1);
          _completed = completed + nextChar;
          continue ;
      default:
        
    }
    _remaining = remaining.slice(1);
    _completed = completed + nextChar;
    continue ;
  };
}

function mockify(inputString) {
  return mockify_helper("", inputString, 0);
}

/*
These lines are automatically generated by the ReScript-to-JS compiler, but causes errors for the Firefox Extension
export {
  swap ,
  mockify_helper ,
  mockify ,
  
}
*/
/* No side effect */
