// Generated by ReScript, PLEASE EDIT WITH CARE


function swap(c, threshold) {
  if (c === " ") {
    return [
            c,
            0
          ];
  } else if (Math.random() < threshold) {
    return [
            c.toLocaleLowerCase(),
            -1
          ];
  } else {
    return [
            c.toLocaleUpperCase(),
            1
          ];
  }
}

function mockify_helper(_done, _remaining, _consecutiveUppers) {
  while(true) {
    var consecutiveUppers = _consecutiveUppers;
    var remaining = _remaining;
    var done = _done;
    if (remaining === "") {
      return done;
    }
    var threshold = 0.5 + consecutiveUppers * 0.17;
    var match = swap(remaining[0], threshold);
    var nextChar = match[0];
    switch (match[1]) {
      case -1 :
          _consecutiveUppers = Math.min(consecutiveUppers - 1 | 0, -1);
          _remaining = remaining.slice(1);
          _done = done + nextChar;
          continue ;
      case 0 :
          break;
      case 1 :
          _consecutiveUppers = Math.max(consecutiveUppers + 1 | 0, 1);
          _remaining = remaining.slice(1);
          _done = done + nextChar;
          continue ;
      default:

    }
    _remaining = remaining.slice(1);
    _done = done + nextChar;
    continue ;
  };
}

function mockify(inputString) {
  return mockify_helper("", inputString, 0);
}
/* No side effect */
